### ISSUE TITLE
Tracking issue for session support

### ISSUE THREAD

**Issue by ubnt-intrepid** [tsukuyomi-rs/tsukuyomi#141]
- [x] initial implementation (in #145)
  - [x] Cookie backend
  - [x] Redis backend
- [ ] add tests and documentation
- [x] (optional) abstraction layer

**Comment by ubnt-intrepid** [comment]
note: currently working on https://github.com/tsukuyomi-rs/tsukuyomi-session
