### ISSUE TITLE
Tracking issue for router API

### ISSUE THREAD

**Issue by ubnt-intrepid** [tsukuyomi-rs/tsukuyomi#53]
- [x] Fallback to default `OPTIONS` handler
- [ ] Add options to enable/disable ignoring the trailing slashes
- [ ] Allows multiple handlers per endpoint.
