### ISSUE TITLE
Tracking issue for code generation

### ISSUE THREAD

**Issue by ubnt-intrepid** [tsukuyomi-rs/tsukuyomi#80]
### Overview

An attribute-style procedural macro is introduced in order to modify the signature of handler functions into an appropriate form to be used by the framework:

```rust
#[handler]
fn handler() -> impl Responder { ... }
```

### Tasks
- [x] Add `tsukuyomi-codegen` and implement the initial support (#78).
- [x] Adjust the core API (some breaking changes may be required).
- [x] (Optional) wait for [`proc_macro`] and [`use_extern_macros`] to be stabilized.
- [ ] Release `tsukuyomi-codegen`

[`proc_macro`]: https://github.com/rust-lang/rust/pull/52081
[`use_extern_macros`]: https://github.com/rust-lang/rust/pull/50911
